### ISSUE TITLE
待填之坑

### ISSUE THREAD

**Issue by idailylife** [idailylife/dwy_website#2]
- [ ] 1. requester/worker实名验证：前端+后端；
- [ ] 2. 短信验证码：后端；
- [ ] 3. 注册、登录、注销：前端；
- [x] 4. 任务大厅：后端；
- [x] 5. 实名认证：前端、后端；
- [ ] 6. 资质认证：前端、后端；
- [ ] 7. 任务发布：前端、后端；
- [ ] 8. ...
- [ ]

**Comment by sanfran1068** [comment]
这个打钩的是填了的还是未填的啊？
